from flask import Flask, jsonify, request, render_template_string, send_from_directory
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import os, json

app = Flask(__name__)

# ── Load data ──────────────────────────────────────────────────────────────────
BASE = os.path.dirname(__file__)

movies_path = os.path.join(BASE, "movies.csv")
ratings_path = os.path.join(BASE, "ratings.csv")

# Optional local poster cache generated by poster_cache.py
poster_cache_path = os.path.join(BASE, "posters.json")
poster_cache = {}
if os.path.exists(poster_cache_path):
    try:
        with open(poster_cache_path, encoding="utf-8") as f:
            poster_cache = json.load(f)
    except Exception:
        poster_cache = {}


if not os.path.exists(movies_path):
    raise FileNotFoundError(f"Missing required dataset file: {movies_path}")
if not os.path.exists(ratings_path):
    raise FileNotFoundError(f"Missing required dataset file: {ratings_path}")

movies  = pd.read_csv(movies_path)
ratings = pd.read_csv(ratings_path)

required_movies_cols = {"movieId","title","genres","director","cast","imdb_rating","year"}
required_ratings_cols = {"userId","movieId","rating"}

missing_movies = required_movies_cols - set(movies.columns)
missing_ratings = required_ratings_cols - set(ratings.columns)

if missing_movies:
    raise ValueError(f"movies.csv missing columns: {sorted(missing_movies)}")
if missing_ratings:
    raise ValueError(f"ratings.csv missing columns: {sorted(missing_ratings)}")


# ── Content-based model ────────────────────────────────────────────────────────
movies["soup"] = (
    movies["genres"].fillna("") + " " +
    movies["director"].fillna("") + " " +
    movies["cast"].fillna("") + " " +
    movies["title"].fillna("")
)
tfidf = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf.fit_transform(movies["soup"])
content_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
movie_idx = pd.Series(movies.index, index=movies["movieId"])

# ── Collaborative-filtering (user-item matrix) ─────────────────────────────────
user_movie = ratings.pivot_table(index="userId", columns="movieId", values="rating").fillna(0)
item_sim = cosine_similarity(user_movie.T)
item_sim_df = pd.DataFrame(item_sim, index=user_movie.columns, columns=user_movie.columns)

# ── Helpers ────────────────────────────────────────────────────────────────────
def movie_to_dict(row):
    movie_id = int(row["movieId"])

    # Prefer local cached posters downloaded by poster_cache.py
    cached = poster_cache.get(str(movie_id)) or poster_cache.get(movie_id) or {}
    poster = cached.get("poster_path") or None

    return {
        "id":       movie_id,
        "title":    row["title"],
        "year":     int(row["year"]) if pd.notna(row["year"]) else None,
        "genres":   row["genres"].split("|") if pd.notna(row["genres"]) else [],
        "director": row["director"] if pd.notna(row["director"]) else "",
        "cast":     row["cast"] if pd.notna(row["cast"]) else "",
        "rating":   float(row["imdb_rating"]) if pd.notna(row["imdb_rating"]) else 0,
        # Fallback: placeholder text (UI still works without poster cache)
        "poster": poster or (
            "https://via.placeholder.com/300x450/c0392b/ffffff?text=" + str(row['title'])[:15].replace(' ','+')
        ),
    }

# ── Routes ─────────────────────────────────────────────────────────────────────
@app.route("/")
def index():
    # Ensure correct encoding (index.html contains Unicode symbols/em-dashes)
    with open(os.path.join(BASE, "index.html"), encoding="utf-8") as f:
        return f.read()


@app.route("/api/movies/search")
def search():
    q = request.args.get("q","").lower().strip()
    if not q:
        return jsonify([])
    mask = (
        movies["title"].str.lower().str.contains(q, na=False) |
        movies["genres"].str.lower().str.contains(q, na=False) |
        movies["director"].str.lower().str.contains(q, na=False) |
        movies["cast"].str.lower().str.contains(q, na=False)
    )
    results = movies[mask].head(20)
    return jsonify([movie_to_dict(r) for _, r in results.iterrows()])

@app.route("/api/movies/top")
def top_movies():
    genre = request.args.get("genre","")
    df = movies.copy()
    if genre and genre != "All":
        df = df[df["genres"].str.contains(genre, na=False, case=False)]
    top = df.sort_values("imdb_rating", ascending=False).head(20)
    return jsonify([movie_to_dict(r) for _, r in top.iterrows()])

@app.route("/api/movies/<int:movie_id>/similar")
def similar_movies(movie_id):
    """Content-based similar movies"""
    if movie_id not in movie_idx.index:
        return jsonify([])
    idx = movie_idx[movie_id]
    scores = list(enumerate(content_sim[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:11]
    recs = movies.iloc[[i for i,_ in scores]]
    return jsonify([movie_to_dict(r) for _, r in recs.iterrows()])

@app.route("/api/recommend/collaborative")
def collaborative():
    """Item-based collaborative filtering for a given movie"""
    movie_id = int(request.args.get("movie_id", 1))
    if movie_id not in item_sim_df.index:
        return jsonify([])
    sim = item_sim_df[movie_id].drop(movie_id).sort_values(ascending=False).head(10)
    rec_ids = sim.index.tolist()
    recs = movies[movies["movieId"].isin(rec_ids)]
    return jsonify([movie_to_dict(r) for _, r in recs.iterrows()])

@app.route("/api/movies/<int:movie_id>")
def movie_detail(movie_id):
    row = movies[movies["movieId"] == movie_id]
    if row.empty:
        return jsonify({"error":"not found"}), 404
    return jsonify(movie_to_dict(row.iloc[0]))


@app.route("/api/genres")
def genres():
    all_genres = set()
    for g in movies["genres"].dropna():
        all_genres.update(g.split("|"))
    return jsonify(sorted(all_genres))

@app.route("/api/stats")
def stats():
    return jsonify({
        "total_movies": len(movies),
        "total_ratings": len(ratings),
        "total_users": ratings["userId"].nunique(),
        "avg_rating": round(ratings["rating"].mean(), 2),
        "top_genre": movies["genres"].str.split("|").explode().value_counts().index[0],
    })

if __name__ == "__main__":
    app.run(debug=True, port=5000)
